name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2019.06.08
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update /app from repository
        run: |
          cp -fr ${GITHUB_WORKSPACE}/app /app/
          cp -fr ${GITHUB_WORKSPACE}/config /app/
          cp -fr ${GITHUB_WORKSPACE}/dist /app/
          cp -fr ${GITHUB_WORKSPACE}/public /app/
      - name: Build
        run: |
          cd /app
          yarn run build
      - name: Update dist
        run: |
          cp -fr /app/dist ${GITHUB_WORKSPACE}/
      - name: Commit & push changes
        uses: actions-x/commit@v2
