name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2019.06.08
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: find /app
        shell: bash
        run: |
          find /app
      - name: find cp app
        shell: bash
        run: |
          echo APP
          find ${GITHUB_WORKSPACE}/app
          echo CONFIG
          find ${GITHUB_WORKSPACE}/config
          echo DIST
          find ${GITHUB_WORKSPACE}/dist
          echo PUBLIC
          find ${GITHUB_WORKSPACE}/public
      - name: setup /app
        shell: bash
        run: |
          cp -fr ${GITHUB_WORKSPACE}/app /app/
          cp -fr ${GITHUB_WORKSPACE}/config /app/
          cp -fr ${GITHUB_WORKSPACE}/dist /app/
          cp -fr ${GITHUB_WORKSPACE}/public /app/
      - name: build
        shell: bash
        run: |
          cd /app
          yarn run build
