name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2019.06.08
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - dist:/app/dist
        - app:/app/app
        - config:/app/config
        - public:/app/public
    steps:
      - name: build
        shell: bash
        run: |
          ls
          cd /app
          yarn run build
