name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2021.03.29
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update /app from repository
        run: |
          cp -fr ${GITHUB_WORKSPACE}/app /app/
          cp -fr ${GITHUB_WORKSPACE}/config /app/
          cp -fr ${GITHUB_WORKSPACE}/dist /app/
          cp -fr ${GITHUB_WORKSPACE}/public /app/
      - name: Build
        run: |
          cd /app
          yarn run build
      - name: Update dist
        run: |
          cp -fr /app/dist ${GITHUB_WORKSPACE}/
      - name: Commit & push changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [ -n "$(git status --porcelain)" ]
          then
            git commit -m "Generate public site

          via https://github.com/timparker/Youll-Soon-Know/runs/${GITHUB_RUN_ID}?check_suite_focus=true

          https://youllsoonknow.us/ will be updated within 5 mins"
            git push
          else
            echo "There is nothing new to commit, we are done ✅"
          fi
