name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2019.06.08
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      volumes:
        - /home/runner/work/Youll-Soon-Know/Youll-Soon-Know/app:/app/app
        - /home/runner/work/Youll-Soon-Know/Youll-Soon-Know/config:/app/config
        - /home/runner/work/Youll-Soon-Know/Youll-Soon-Know/dist:/app/dist
        - /home/runner/work/Youll-Soon-Know/Youll-Soon-Know/public:/app/public
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: build
        shell: bash
        run: |
          cd /app
          yarn run build
