name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  dist:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2021.03.29
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --user root
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Update /app from repository
        run: |
          cp -fr ${GITHUB_WORKSPACE}/app /app/
          cp -fr ${GITHUB_WORKSPACE}/config /app/
          cp -fr ${GITHUB_WORKSPACE}/dist /app/
          cp -fr ${GITHUB_WORKSPACE}/public /app/
      - name: Build
        run: |
          cd /app
          yarn run build
      - name: Update dist
        run: |
          cp -fr /app/dist ${GITHUB_WORKSPACE}/
      - name: Commit & push changes
        run: |
          pwd
          git remote -v
          ls -lah
          git config --list
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update dist"
          git push
