name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ] 
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker://ghcr.io/gerhard/ghcr.io/youllsoonknow:2019.06.08
      - name: build
        run: |
          pwd
          ls
          type yarn
          find .
