name: dist
on:
  push:
    branches: [ master ]
    paths-ignore: [ 'dist/**' ]
  # Allows you to run this workflow manually from the Actions tab
  # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/timparker/youllsoonknow:2019.06.08
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PACKAGES_ACCESS_TOKEN }}
      volumes:
        - $PWD:/app
      options: --user root
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: build
        shell: bash
        run: |
          echo WORKFLOW
          find /github/workflow
          echo WORKDIR
          find /__w
          echo APP
          find /app
          cd /app
          yarn run build
